name: PR Review Notification with Diff

on:
  pull_request:
    types: [ready_for_review]

jobs:
  notify-api:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR Review and Diff to API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/github-script@v7
        with:
          script: |
            const githubToken = process.env.GITHUB_TOKEN;
            const prReview = context.payload;
            const prNumber = context.payload.number;
            const repoFullName = context.payload.repository.full_name;
            const [repoOwner, repoName] = repoFullName.split('/');

            // Function to post comment
            async function postComment(commentBody) {
              const commentPayload = {
                owner: repoOwner,
                repo: repoName,
                issue_number: prNumber,
                body: commentBody,
              };
              await github.rest.issues.createComment(commentPayload);
            }

            // Function to make API request
            async function makeApiRequest(url, method, body) {
              const response = await fetch(url, {
                method: method,
                headers: {
                  'Content-Type': 'application/json',
                  'Authorization': `Bearer ${githubToken}`,
                },
                body: JSON.stringify(body),
              });
              return response.json();
            }

            // Main function to handle the workflow
            async function main() {
              try {
                // Get PR diff
                const diffResponse = await github.rest.pulls.get({
                  owner: repoOwner,
                  repo: repoName,
                  pull_number: prNumber,
                  mediaType: {
                    format: 'diff',
                  },
                });
                const prDiff = diffResponse.data;

                const addApiEndpoint = 'https://code-digester-006167766c6e.herokuapp.com/llm/add-pr-data';
                const generatePrEndpoint = 'https://code-digester-006167766c6e.herokuapp.com/llm/generate-pr-eval';

                // Customize this payload as needed
                const payload = {
                  prNumber: prNumber,
                  repoName: repoName,
                  reviewId: prReview.id,
                  reviewState: prReview.state,
                  reviewBody: prReview.body,
                  prDiff: prDiff,
                };

                console.log({payload})

                // Make the API requests
                const addDataRes = await makeApiRequest(addApiEndpoint, 'POST', payload);
                console.dir({addDataRes})
                const data = await makeApiRequest(generatePrEndpoint, 'POST', { prDiff });
                const groupedResult = data.result.data.Get.PrData[0]._additional.generate.groupedResult;
                const commentBody = groupedResult;
                await postComment(commentBody);
                
                console.log(`Comment posted`);
              } catch (error) {
                console.error(error);
              }
            }

            // Execute the main function
            main();
