name: PR Review Notification with Diff

on:
  pull_request_review:
    types: [submitted, edited, dismissed]

jobs:
  notify-api:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR Review and Diff to API
        env:
          GITHUB_TOKEN: ${{ github.token }}
        uses: actions/github-script@v6
        with:
          script: |
            const axios = require('axios');
            const githubToken = process.env.GITHUB_TOKEN;
            const prReview = context.payload.review;
            const prNumber = context.payload.pull_request.number;
            const repoName = context.payload.repository.full_name;
            const repoOwner = context.payload.repository.owner.login;

            // GitHub API endpoint to get the PR diff
            const diffUrl = `https://api.github.com/repos/${repoOwner}/${repoName}/pulls/${prNumber}`;

            // Fetch PR diff
            const diffResponse = await axios.get(diffUrl, {
              headers: {
                'Accept': 'application/vnd.github.v3.diff',
                'Authorization': `Bearer ${githubToken}`
              }
            }).catch(error => console.error(`Failed to fetch PR diff: ${error.toString()}`));

            const prDiff = diffResponse ? diffResponse.data : 'Diff not available';

            // Define your API endpoint here
            const apiEndpoint = 'https://code-digester-006167766c6e.herokuapp.com/llm/add-pr-data';

            // Customize this payload as needed
            const payload = {
              prNumber: prNumber,
              repoName: repoName,
              reviewId: prReview.id,
              reviewState: prReview.state,
              reviewBody: prReview.body,
              prDiff: prDiff, // Including the PR diff in the payload
            };

            // Make the API request
            axios.post(apiEndpoint, payload)
              .then(response => console.log(`Status: ${response.status}`))
              .catch(error => console.error(`Error: ${error.toString()}`));
